### ISSUE TITLE
Proposal for simplified output of Normalize

### ISSUE THREAD

**Issue by gebsl** [Glartek/senml-js#6]
Hi @marcotuna,

while using `Normalize` I noticed that all the base values are still present in the resulting, normalized document. As these base values are all set to default values (`0` or `''`) I was thinking whether it makes sense to remove them completely, as I think one is not interested in base values after normalization.
This would have the nice side-effect that output becomes smaller and also tests would become easier to write, as one does not have to include base values with default values anymore.

What do you think about the proposal to remove all the base values from the result in `Normalize`.

Best regards,
Gabriel

**Comment by marcotuna** [comment]
Hi @gebsl 
Yes, ideally values that are not populated shouldn't be present, that's also how the original library in Golang behaves. 
I will keep this Issue open to track the progress of this matter.
Thanks for raising this!

**Comment by marcotuna** [comment]
Closing this issue. Resolved on https://github.com/Glartek/senml-js/pull/9
